### ISSUE TITLE
大众点评评论爬取疑问

### ISSUE THREAD

**Issue by zhangyixinSarah** [skipmaple/Mitchell#1]
作者，您好。我用了您分享在GitHub上的程序，
![6802ff419f75b13cdba20f7a8dd66de](https://user-images.githubusercontent.com/56244274/146972579-41035bb5-950c-434a-b263-f5d213abc8fc.png)

我在使用中，遇到这样的问题，
我用WAMP搭建了MySql的数据库，现在已经连接成功了，但现在你在初始化设置self函数上，使用了
from pymongo import MongoClient 
这mongo的一些设置，比如
self.client = MongoClient(MONGO_CLIENT)
这样的命令，在我pyCharm中运行，在这mongo上会报错，截图如下
![61840c2326c24f084f6552f976eba89](https://user-images.githubusercontent.com/56244274/146972650-e6d2df80-8e46-4b74-a9aa-7e6ff7acb93d.png)
所以，程序应该在初始化阶段就报错停止 了

以上
此致
name: Yixin Zhang 
email: bobikeke@qq.com
wechat: zyx1234567890zyx

**Comment by skipmaple** [comment]
你好，张同学 👋

非常感谢你的使用，刚刚看到这个issue里代码的报错信息：

它的报错信息是 `第1页反爬验证!`
触发这个报错的代码位置在 [dian_ping.py 154行](https://github.com/skipmaple/Mitchell/blob/main/dian_ping.py#L154-L156)
```python
if response.url.find('verify') > -1:
    print("第 %d 页反爬验证！" % i)
    break
```
根据之前我使用的经验，应该是触发了大众点评的反爬机制(不是mongo的问题)

**建议**去网页上退出点评网的账号，重新登录一下获取新的`cookie`填入[config.py](https://github.com/skipmaple/Mitchell/blob/main/config.py)

如果还是不行，可以换一个点评网的账号试试。或者继续回复这个issue，看到就会回复您。

再次非常感谢你的反馈🤝

**Comment by zhangyixinSarah** [comment]
尊敬的先生，


您好，感谢您的回答，我已经通过您的方法，成功爬取大众点评的数据了~不过现在貌似有个新问题，IndexError: list index out of range，我确保每次都是登陆和验证好的。请问，你认为是url的问题，还是其他什么问题呢？谢谢！












此致

张同学

&nbsp;


&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "skipmaple/Mitchell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 晚上10:16
***@***.***&gt;;
抄送:&nbsp;"Yixin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [skipmaple/Mitchell] 大众点评评论爬取疑问 (Issue #1)





 
你好，张同学 👋
 
非常感谢你的使用，刚刚看到这个issue里代码的报错信息：
 
它的报错信息是 第1页反爬验证!
 触发这个报错的代码位置在 dian_ping.py 154行
 if response.url.find('verify') &gt; -1:     print("第 %d 页反爬验证！" % i)     break
 
根据之前我使用的经验，应该是触发了大众点评的反爬机制(不是mongo的问题)
 
建议去网页上退出点评网的账号，重新登录一下获取新的cookie填入config.py
 
如果还是不行，可以换一个点评网的账号试试。或者继续回复这个issue，看到就会回复您。
 
再次非常感谢你的反馈🤝
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by skipmaple** [comment]
> 尊敬的先生， 您好，感谢您的回答，我已经通过您的方法，成功爬取大众点评的数据了~不过现在貌似有个新问题，IndexError: list index out of range，我确保每次都是登陆和验证好的。请问，你认为是url的问题，还是其他什么问题呢？谢谢！ 此致 张同学 &nbsp; &nbsp;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "skipmaple/Mitchell" ***@***.***&gt;; 发送时间:&nbsp;2021年12月22日(星期三) 晚上10:16 ***@***.***&gt;; 抄送:&nbsp;"Yixin ***@***.******@***.***&gt;; 主题:&nbsp;Re: [skipmaple/Mitchell] 大众点评评论爬取疑问 (Issue #1) 你好，张同学 👋 非常感谢你的使用，刚刚看到这个issue里代码的报错信息： 它的报错信息是 第1页反爬验证! 触发这个报错的代码位置在 dian_ping.py 154行 if response.url.find('verify') &gt; -1: print("第 %d 页反爬验证！" % i) break 根据之前我使用的经验，应该是触发了大众点评的反爬机制(不是mongo的问题) 建议去网页上退出点评网的账号，重新登录一下获取新的cookie填入config.py 如果还是不行，可以换一个点评网的账号试试。或者继续回复这个issue，看到就会回复您。 再次非常感谢你的反馈🤝 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以发一下报错的截图吗

**Comment by zhangyixinSarah** [comment]
Sincerely yours,

Yixin Zhang,

School of Architecture, Tsinghua University, Beijing, China

***@***.***

&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "skipmaple/Mitchell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 晚上11:33
***@***.***&gt;;
抄送:&nbsp;"Yixin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [skipmaple/Mitchell] 大众点评评论爬取疑问 (Issue #1)





  
尊敬的先生， 您好，感谢您的回答，我已经通过您的方法，成功爬取大众点评的数据了~不过现在貌似有个新问题，IndexError: list index out of range，我确保每次都是登陆和验证好的。请问，你认为是url的问题，还是其他什么问题呢？谢谢！ 此致 张同学 &nbsp; &nbsp;

 ------------------ 原始邮件 ------------------ 发件人: "skipmaple/Mitchell" @.&gt;; 发送时间:&nbsp;2021年12月22日(星期三) 晚上10:16 @.&gt;; 抄送:&nbsp;"Yixin @.@.&gt;; 主题:&nbsp;Re: [skipmaple/Mitchell] 大众点评评论爬取疑问 (Issue #1) 你好，张同学 👋 非常感谢你的使用，刚刚看到这个issue里代码的报错信息： 它的报错信息是 第1页反爬验证! 触发这个报错的代码位置在 dian_ping.py 154行 if response.url.find('verify') &gt; -1: print("第 %d 页反爬验证！" % i) break 根据之前我使用的经验，应该是触发了大众点评的反爬机制(不是mongo的问题) 建议去网页上退出点评网的账号，重新登录一下获取新的cookie填入config.py 如果还是不行，可以换一个点评网的账号试试。或者继续回复这个issue，看到就会回复您。 再次非常感谢你的反馈🤝 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可以发一下报错的截图吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyixinSarah** [comment]
不好意思，刚刚发送了空白邮件，截屏补充在此，还请您多多指教~问题：IndexError: list index out of range，我确保每次都是登陆和验证好的，也确保是英文输入法。请问，您认为是url的问题，还是其他什么问题呢？我有些怀疑是不是VPN设置的问题，之前改成过“安全模式”，不过现在改回“极速模式”了，原来能爬，现在却突然不能爬了，请问您觉得是什么原因呢？
url:&nbsp;INIT_URL = 'http://www.dianping.com/shop/k4pqn0e1PFgt0O2G/review_all/p{}?queryType=isPic&amp;queryVal=true'





Sincerely yours,

Yixin Zhang,

School of Architecture, Tsinghua University, Beijing, China

***@***.***

&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yixin ZHANG张译心"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月25日(星期六) 上午10:32
***@***.***&gt;;

主题:&nbsp;回复： [skipmaple/Mitchell] 大众点评评论爬取疑问 (Issue #1)









Sincerely yours,

Yixin Zhang,

School of Architecture, Tsinghua University, Beijing, China

***@***.***

&nbsp;


&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "skipmaple/Mitchell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 晚上11:33
***@***.***&gt;;
抄送:&nbsp;"Yixin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [skipmaple/Mitchell] 大众点评评论爬取疑问 (Issue #1)





  
尊敬的先生， 您好，感谢您的回答，我已经通过您的方法，成功爬取大众点评的数据了~不过现在貌似有个新问题，IndexError: list index out of range，我确保每次都是登陆和验证好的。请问，你认为是url的问题，还是其他什么问题呢？谢谢！ 此致 张同学 &nbsp; &nbsp;

 ------------------ 原始邮件 ------------------ 发件人: "skipmaple/Mitchell" @.&gt;; 发送时间: 2021年12月22日(星期三) 晚上10:16 @.&gt;; 抄送: "Yixin @.@.&gt;; 主题: Re: [skipmaple/Mitchell] 大众点评评论爬取疑问 (Issue #1) 你好，张同学 👋 非常感谢你的使用，刚刚看到这个issue里代码的报错信息： 它的报错信息是 第1页反爬验证! 触发这个报错的代码位置在 dian_ping.py 154行 if response.url.find('verify') &gt; -1: print("第 %d 页反爬验证！" % i) break 根据之前我使用的经验，应该是触发了大众点评的反爬机制(不是mongo的问题) 建议去网页上退出点评网的账号，重新登录一下获取新的cookie填入config.py 如果还是不行，可以换一个点评网的账号试试。或者继续回复这个issue，看到就会回复您。 再次非常感谢你的反馈🤝 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可以发一下报错的截图吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by skipmaple** [comment]
> 

应该是触发了点评网的风控机制（好像短时间内大量爬取就会触发），一般一天左右会解封。
你可以通过增加爬取每条数据之间的时间间隔来避免触发（比如增加 sleep 3s）。
或者多准备几个账号，爬取时用账号池来切换。

以上，希望对你有帮助~

**Comment by skipmaple** [comment]
由于很长时间没有回复，所以我关闭了这个Issue。
有其他问题可以再讨论。🤜🤛
