### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by xigua222** [skipmaple/Mitchell#2]
您好，我是一个初学者，尝试您的程序时，在提示“第一页提示反爬验证”后程序就中止了，相关数据不知道保存在哪里，希望得到您的帮助和解答，非常感谢
<img width="864" alt="image" src="https://user-images.githubusercontent.com/52056870/166451299-48a04e1d-17aa-469c-b649-667f632a7be1.png">

**Comment by skipmaple** [comment]
你好👋，出现反爬验证的提示后程序没有继续往下运行，所以还没有走到存数据那一步。

**出现反爬验证的原因：**

短时间内您填入token的账号频繁请求点评网接口（比如5分钟内请求了100次），这种情况账号(对应token)可能被风控查到冷却一段时间

**解决办法:**

1.  换一个账号填入token
2. 切换别的网络

ps: 我之前遇到这种情况，该token对应的账号可能需要一天时间解封禁

以上希望可以帮助到你

**Comment by xigua222** [comment]
> 

感谢！更换cookies后解决了，~~应该是我调试各种库的时候测试太多回了😭~~
但目前只能爬到第一页，第二页开始就没有内容了，请问是有什么限制吗
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/52056870/166457567-55142b1d-a2bd-43c5-b282-75f7adabdece.png">
**再次感谢您的帮助！**

**Comment by skipmaple** [comment]
> > 
> 
> 感谢！更换cookies后解决了，~应该是我调试各种库的时候测试太多回了😭~ 但目前只能爬到第一页，第二页开始就没有内容了，请问是有什么限制吗 <img alt="image" width="1040" src="https://user-images.githubusercontent.com/52056870/166457567-55142b1d-a2bd-43c5-b282-75f7adabdece.png"> **再次感谢您的帮助！**

感觉像是 config.py 中 init_url 格式不太对，可以贴出来看看吗🤝

**Comment by skipmaple** [comment]
![Screen Shot 2022-05-03 at 21 23 50](https://user-images.githubusercontent.com/49176897/166461247-24b6793d-4d87-47cf-875d-b1d71677a116.png)

只需要替换红框中 的值，链接的后半部分需要保留

**Comment by xigua222** [comment]
是的，刚发现我把后面的部分也删掉了orz
但如果保留这个完整链接后，运行时不知为何会报错
<img width="681" alt="image" src="https://user-images.githubusercontent.com/52056870/166463887-1789d4ae-fc4e-4faa-8b9f-63f98989a3c4.png">
（运行结果）
<img width="582" alt="image" src="https://user-images.githubusercontent.com/52056870/166463949-22d918cd-a6b2-41ba-b6ca-88bd51ca6aa1.png">

**Comment by skipmaple** [comment]
`review_all{}` => `review_all/p{}`

你的链接里中括号前面没有加`p`，加一下再试试

**Comment by xigua222** [comment]
是的！解决了！！！
**非常感谢您！！** 🥰
